kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operate-hooks
  namespace: default
subjects:
- kind: ServiceAccount
  name: node-webhook
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: hook-operator # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io