apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: git-to-k8s
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/sfxworks/git-to-k8s.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker.io/quantomworks/git-to-k8s:latest
          timeout: 10m
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
            autoscaling.knative.dev/maxScale: "2"
        spec:
          container:
            image: docker.io/quantomworks/git-to-k8s:latest
            imagePullPolicy: Always
            env:
            - name: WEBHOOK_PATH
              value: "webhook"
            - name: WEBHOOK_SECRET
              value: "super-secret"