apiVersion: v1
kind: Pod
metadata:
  name: node-webhook
  labels:
    app: node-webhook
spec:
  serviceAccountName: node-webhook
  containers:
  - name: node
    image: gcr.io/allthingssfx/hook-to-k8s
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-webhook
  name: node-webhook-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-webhook