apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-build
  annotations:
    hook-to-k8s: af5fd1f11e0620a223162fea3cca91241b14aeb2
spec:
  nodeSelector:
    type: vps
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/mcserverhosting-net/site
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: docker.io/quantomworks/mcsh-site
